set(EXTENSION_LIST azure delta duckdb fts httpfs iceberg json llm postgres sqlite unity_catalog vector neo4j algo tantivy_fts)

#set(EXTENSION_STATIC_LINK_LIST fts)
string(JOIN ", " joined_extensions ${EXTENSION_STATIC_LINK_LIST})
message(STATUS "Static link extensions: ${joined_extensions}")
foreach(extension IN LISTS EXTENSION_STATIC_LINK_LIST)
    add_static_link_extension(${extension})
endforeach()

if(${BUILD_WASM})
    message(STATUS "Building for WASM, extension static linking is enabled by default")
    # fts removed: tantivy_fts replaces it with fuzzy support
    add_static_link_extension(json)
    add_static_link_extension(vector)
    add_static_link_extension(algo)
    add_static_link_extension(tantivy_fts)
endif()

if(ANDROID_ABI)
    message(STATUS "Building for Android, extension static linking is enabled by default")
    add_static_link_extension(fts)
    add_static_link_extension(json)
    add_static_link_extension(vector)
    add_static_link_extension(algo)
    add_static_link_extension(tantivy_fts)
endif()

if(${BUILD_SWIFT})
    message(STATUS "Building for Swift binding, extension static linking is enabled by default")
    add_static_link_extension(fts)
    add_static_link_extension(json)
    add_static_link_extension(vector)
    add_static_link_extension(algo)
    add_static_link_extension(tantivy_fts)
endif()
