#include "main/tantivy_fts_extension.h"
#include "tantivy_fts.h"   // C header generated by cbindgen
#include "main/client_context.h"

namespace kuzu {
namespace tantivy_fts_extension {

void TantivyFtsExtension::load(main::ClientContext* /*context*/) {
    // Stub: verify that Rust FFI symbols are resolvable at link time.
    // No Cypher functions yet.
    (void)tantivy_create_index;
    (void)tantivy_close_index;
    (void)tantivy_search;
}

} // namespace tantivy_fts_extension
} // namespace kuzu

#if defined(BUILD_DYNAMIC_LOAD)
extern "C" {
#if defined(_WIN32)
#define INIT_EXPORT __declspec(dllexport)
#else
#define INIT_EXPORT __attribute__((visibility("default")))
#endif
INIT_EXPORT void init(kuzu::main::ClientContext* context) {
    kuzu::tantivy_fts_extension::TantivyFtsExtension::load(context);
}
INIT_EXPORT const char* name() {
    return kuzu::tantivy_fts_extension::TantivyFtsExtension::EXTENSION_NAME;
}
}
#endif
