//! **Les fichiers générés**, écartés de l'indexation avec leur raison.
//!
//! Un analyseur ANTLR de plusieurs centaines de Ko, un `*_onnx.rs` sorti d'un
//! convertisseur, une table de données Unicode n'apprennent rien à un agent
//! et gonflent le graphe. Comme un secret probable, un fichier généré ne
//! s'écarte pas en silence : la règle a un nom, l'estimation la compte
//! (« 88 écartés : généré — marqueur en tête de fichier ») et le manifeste
//! peut la lever ou la régler.
//!
//! La règle est **une politique déclarée**, pas une liste pour le code : un
//! dossier de documents a ses propres générés (exports, journaux), et les
//! nomme dans les mêmes champs.
//!
//! Elle ne vaut que pour l'indexation et son estimation. Lire, lister ou
//! chercher par motif dans un fichier généré reste permis : il existe, on
//! n'en fait simplement pas des scopes.
//!
//! Deux signaux aujourd'hui, mesurés sur ce dépôt le 4 octobre 2026 :
//! 88 fichiers et 5,2 Mo pour le marqueur en tête, sans faux positif hors des
//! dossiers de tiers ; 14 fichiers et 1,7 Mo pour le dossier `generated`.
//! Le troisième signal proposé — une grosse taille pour très peu de scopes —
//! demande l'analyse et n'est pas ici : la taille seule écarterait un gros
//! fichier écrit à la main.

use serde::{Deserialize, Serialize};

/// Le service sous lequel un backend range la politique de son manifeste.
pub const GENERATED_POLICY_SERVICE: &str = "generated_policy";

pub const REASON_MARKER: &str = "généré — marqueur en tête de fichier";
pub const REASON_DIR: &str = "généré — dossier déclaré";

/// La clé `workspace.generated` d'un manifeste. Absente : les défauts.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GeneratedPolicy {
    /// Écarter les fichiers générés. `false` lève la règle entière.
    pub skip: bool,
    /// Les noms de dossier qui ne tiennent que du généré, où qu'ils soient
    /// dans le chemin.
    pub dirs: Vec<String>,
    /// Les marqueurs cherchés dans la tête du fichier, **casse comprise** :
    /// « DO NOT EDIT » annonce un fichier généré, « Do not modify string
    /// representations » est un commentaire (`pybind11.h`, écarté à tort
    /// par une règle sans casse).
    pub markers: Vec<String>,
    /// Les débuts de ligne qui annoncent un fichier généré, casse comprise,
    /// une fois passés les signes de commentaire. Plus stricts que les
    /// marqueurs : « generated by » au milieu d'une phrase est de la prose.
    pub line_starts: Vec<String>,
    /// Combien d'octets de tête sont lus.
    pub head_bytes: usize,
}

impl Default for GeneratedPolicy {
    fn default() -> Self {
        let owned = |items: &[&str]| items.iter().map(|s| s.to_string()).collect();
        Self {
            skip: true,
            dirs: owned(&["generated"]),
            markers: owned(&[
                "@generated",
                "auto-generated",
                "Auto-generated",
                "AUTO-GENERATED",
                "autogenerated",
                "Autogenerated",
                "automatically generated",
                "Automatically generated",
                "DO NOT EDIT",
                "DO NOT MODIFY",
            ]),
            line_starts: owned(&["Generated by", "Generated from", "Code generated by", "This file is generated", "This file was generated"]),
            head_bytes: 2048,
        }
    }
}

impl GeneratedPolicy {
    /// La règle levée : rien n'est écarté.
    pub fn off() -> Self {
        Self { skip: false, ..Self::default() }
    }

    /// La tête d'un contenu, coupée sur une frontière de caractère.
    pub fn head<'a>(&self, content: &'a str) -> &'a str {
        let mut end = self.head_bytes.min(content.len());
        while !content.is_char_boundary(end) {
            end -= 1;
        }
        &content[..end]
    }

    /// Ce que le chemin seul dit, sans rien lire.
    pub fn reason_by_path(&self, path: &str) -> Option<&'static str> {
        if !self.skip {
            return None;
        }
        let mut parts: Vec<&str> = path.split('/').collect();
        parts.pop();
        parts.iter().any(|part| self.dirs.iter().any(|d| d == part)).then_some(REASON_DIR)
    }

    /// Pourquoi ce fichier est tenu pour généré, ou `None`. `head` : le début
    /// du contenu ([`Self::head`]) ; le chemin est jugé d'abord.
    pub fn reason(&self, path: &str, head: &str) -> Option<&'static str> {
        if !self.skip {
            return None;
        }
        if let Some(reason) = self.reason_by_path(path) {
            return Some(reason);
        }
        let head = self.head(head);
        if self.markers.iter().any(|m| head.contains(m.as_str())) {
            return Some(REASON_MARKER);
        }
        let announced = head.lines().any(|line| {
            let text = line.trim_start_matches(|c: char| c.is_whitespace() || "/*#;-!<".contains(c));
            self.line_starts.iter().any(|s| text.starts_with(s.as_str()))
        });
        announced.then_some(REASON_MARKER)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn un_marqueur_en_tete_ecarte_et_dit_pourquoi() {
        let p = GeneratedPolicy::default();
        assert_eq!(p.reason("src/parser.cpp", "// Generated from Cypher.g4 by ANTLR 4.13.1\n#include <x>"), Some(REASON_MARKER));
        assert_eq!(p.reason("src/types.rs", "// @generated by a tool\npub struct A;"), Some(REASON_MARKER));
        assert_eq!(p.reason("a.c", "/* This file was generated automatically by the Snowball to ISO C compiler */"), Some(REASON_MARKER));
        assert_eq!(p.reason("a.py", "# DO NOT EDIT — written by build.py\n"), Some(REASON_MARKER));
    }

    #[test]
    fn de_la_prose_qui_dit_generated_n_est_pas_un_marqueur() {
        let p = GeneratedPolicy::default();
        // Les trois faux positifs d'une règle lâche, trouvés sur ce dépôt.
        assert_eq!(p.reason("README.md", "this iceberg table is generated by using DuckDB (v0.7.0)"), None);
        assert_eq!(p.reason("bound_import_database.h", "// The queries below are\n// generated by exporting the database, resulting in queries"), None);
        assert_eq!(p.reason("src/embed.rs", "/// Vectors generated by the model are normalised.\nfn f() {}"), None);
        assert_eq!(p.reason("pybind11.h", "    // Do not modify string representations\n"), None);
    }

    #[test]
    fn le_marqueur_ne_se_cherche_qu_en_tete() {
        let p = GeneratedPolicy { head_bytes: 32, ..Default::default() };
        let content = format!("{}\n// @generated\n", "x".repeat(64));
        assert_eq!(p.reason("a.rs", &content), None);
        // Une tête coupée au milieu d'un caractère ne panique pas.
        let accents = "é".repeat(40);
        assert_eq!(p.head(&accents).len(), 32);
    }

    #[test]
    fn un_dossier_declare_ecarte_sans_rien_lire() {
        let p = GeneratedPolicy::default();
        assert_eq!(p.reason_by_path("extension/rag3weaver/generated/bge_m3_onnx.rs"), Some(REASON_DIR));
        assert_eq!(p.reason_by_path("src/generated.rs"), None, "le nom d'un fichier n'est pas un dossier");
        // Un dossier de documents nomme les siens.
        let docs = GeneratedPolicy { dirs: vec!["exports".into(), "journaux".into()], ..Default::default() };
        assert_eq!(docs.reason_by_path("clients/exports/2026-09.md"), Some(REASON_DIR));
        assert_eq!(docs.reason_by_path("generated/a.md"), None);
    }

    #[test]
    fn la_regle_se_leve() {
        let p = GeneratedPolicy::off();
        assert_eq!(p.reason("generated/a.rs", "// @generated"), None);
        let declared: GeneratedPolicy = serde_json::from_str(r#"{"skip": false}"#).unwrap();
        assert_eq!(declared, p);
        assert!(serde_json::from_str::<GeneratedPolicy>(r#"{"skipp": false}"#).is_err(), "une clé inconnue se refuse");
    }
}
