// Fichier généré par scripts/mots_reserves.py depuis la grammaire du moteur
// (src/antlr4/keywords.txt moins kU_NonReservedKeywords de Cypher.g4).
// Ne pas éditer à la main : relancer le script.

/// Les mots que la grammaire de rag3db refuse comme nom de table, de
/// relation ou de champ, en majuscules.
pub const RAG3DB_RESERVED_WORDS: &[&str] = &[
    "ACYCLIC",
    "ALL",
    "AND",
    "ANY",
    "ASC",
    "ASCENDING",
    "CASE",
    "CAST",
    "COLUMN",
    "COMMIT_SKIP_CHECKPOINT",
    "CREATE",
    "DBTYPE",
    "DEFAULT",
    "DESC",
    "DESCENDING",
    "DISTINCT",
    "ELSE",
    "END",
    "ENDS",
    "EXISTS",
    "FALSE",
    "GLOB",
    "GROUP",
    "HEADERS",
    "HINT",
    "IN",
    "INSTALL",
    "JOIN",
    "MACRO",
    "MULTI_JOIN",
    "NONE",
    "NOT",
    "NULL",
    "ON",
    "ONLY",
    "OPTIONAL",
    "OR",
    "ORDER",
    "PRIMARY",
    "PROFILE",
    "ROLLBACK_SKIP_CHECKPOINT",
    "SHORTEST",
    "SINGLE",
    "STARTS",
    "TABLE",
    "THEN",
    "TRAIL",
    "TRUE",
    "UNION",
    "UNWIND",
    "WHEN",
    "WHERE",
    "WITH",
    "WSHORTEST",
    "XOR",
];
