name: LDBC Fintech Benchmark

on:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:
    inputs:
      scale_factor:
        description: 'Scale factor'
        required: true
        default: "1"
        type: choice
        options:
          - "1"
          - "10"

jobs:
  benchmark:
    name: ldbc-fintech-benchmark
    runs-on: rag3db-self-hosted-benchmarking-xl
    env:
      NUM_THREADS: 128
      GEN: Ninja
    steps:
      - name: Set env for scheduled run
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "SCALE_FACTOR=1" >> $GITHUB_ENV

      - name: Set env for workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "SCALE_FACTOR=${{ github.event.inputs.scale_factor }}" >> $GITHUB_ENV

      - name: Set checkout dir
        run: |
          echo "RAG3DB_DIR=$(pwd)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Build rag3db
        run: |
          pip3 install -r tools/python_api/requirements_dev.txt
          make python
          make java
    
      - name: Clone implementation
        uses: actions/checkout@v4
        with:
          repository: rag3db/ldbc_finbench_transaction_impls
          token: ${{ secrets.DOC_PUSH_TOKEN }}
          path: ldbc_finbench_transaction_impls
      
      - name: Update implementation
        working-directory: ldbc_finbench_transaction_impls
        run: |
          ln -s $RAG3DB_DIR/tools/java_api/build/rag3db_java.jar rag3db/src/main/resources/rag3db_java.jar
          ln -s $RAG3DB_DIR/tools/python_api/build/rag3db rag3db/scripts/rag3db
          mkdir -p rag3db/src/main/resources/data
          ln -s $CSV_DIR/finbench-datasets/sf${SCALE_FACTOR} rag3db/src/main/resources/data/sf${SCALE_FACTOR}
          mvn clean package -DskipTests

      - name: Load data
        working-directory: ldbc_finbench_transaction_impls
        run: python3 rag3db/scripts/import_data.py sf${SCALE_FACTOR}

      - name: Run benchmark
        working-directory: ldbc_finbench_transaction_impls/rag3db
        run:
          java -cp target/rag3db-0.1.0-alpha.jar:target/classes/rag3db_java.jar org.ldbcouncil.finbench.driver.driver.Driver -P sf${SCALE_FACTOR}_finbench_benchmark.properties | tee LDBC-FinBench.log
     
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: LDBC-FinBench-results
          path: ldbc_finbench_transaction_impls/rag3db/results/LDBC-FinBench-results.json

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: LDBC-FinBench-logs
          path: ldbc_finbench_transaction_impls/rag3db/LDBC-FinBench.log
    
      - name: Report result to server
        working-directory: ldbc_finbench_transaction_impls
        run: |
          python3 rag3db/scripts/report_results.py
