name: Build Mac Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  build-precompiled-bin-universal:
    runs-on: self-hosted-mac-x64
    steps:
      - uses: actions/checkout@v4
      
      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build universal precompiled binaries
        run: |
          make NUM_THREADS=$(sysctl -n hw.ncpu)
          make install
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"

      - name: Collect artifacts
        run: |
          mv install/include/rag3db.h .
          mv install/include/rag3db.hpp .
          mv install/lib/librag3db.dylib .
          mv install/bin/rag3db .

      - name: Verify binary information
        run: |
          file -b rag3db
          otool -l rag3db | grep minos
          file -b librag3db.dylib
          otool -l librag3db.dylib | grep minos

      - name: Create tarball
        run: |
          tar -czvf librag3db-osx-universal.tar.gz rag3db.h rag3db.hpp librag3db.dylib
          tar -czvf rag3db_cli-osx-universal.tar.gz rag3db

      - uses: actions/upload-artifact@v4
        with:
          name: librag3db-osx-universal
          path: librag3db-osx-universal.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: rag3db_cli-osx-universal
          path: rag3db_cli-osx-universal.tar.gz
