name: Build Windows Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-precompiled-bin:
    runs-on: self-hosted-windows
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: ./scripts

      - name: Build precompiled binaries
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          make NUM_THREADS=%NUMBER_OF_PROCESSORS%
          make install

      - name: Collect artifacts
        shell: cmd
        run: |
          move install\include\rag3db.h
          move install\include\rag3db.hpp
          move install\bin\rag3db_shared.dll
          move install\lib\rag3db_shared.lib
          move install\bin\rag3db_shell.exe rag3db.exe

      - uses: actions/upload-artifact@v4
        with:
          name: librag3db-windows-x86_64
          path: |
            rag3db.h
            rag3db.hpp
            rag3db_shared.dll
            rag3db_shared.lib

      - uses: actions/upload-artifact@v4
        with:
          name: rag3db_cli-windows-x86_64
          path: rag3db.exe
